--- #YAML:1.0
name:               MojoX-Locale-Maketext
version:            0.06
abstract:           Locale::Maketext implementation
author:
    - Viacheslav Tykhanovskyi <vti@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Locale::Maketext:  0
    Mojo:              0.991250
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
